version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:8.0.1-alpine
    restart: on-failure
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - hyperion

  redis-commander:
    profiles:
      - tools
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8089:8081"
    networks:
      - hyperion

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.0-management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_VHOST}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hyperion

  mongodb:
    container_name: mongodb
    image: mongo:8.0.9
    restart: on-failure
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
    # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - hyperion

volumes:
  rabbitmq:
    driver: local
  redis:
    driver: local
  mongo:
    driver: local

networks:
  hyperion:
    external: true
