version: "3.8"
services:
  indexer:
    build: .
    # restart: on-failure
    ports:
      - "7001:7001"
    volumes:
      - ./config/chains/:/hyperion-history-api/config/chains/
      - ./config/connections.json:/hyperion-history-api/config/connections.json
    networks:
      - hyperion
    #command: ./run.sh local-indexer

  api:
    build: .
    ports:
      - "7000:7000"
    depends_on:
      - indexer
    volumes:
      - ./config/chains/:/hyperion-history-api/config/chains/
      - ./config/connections.json:/hyperion-history-api/config/connections.json
    networks:
      - hyperion
    #command: ./run.sh local-api

networks:
  hyperion:
    external: true
